### ISSUE TITLE
[FEAT]: 코드 리팩토링

### ISSUE THREAD

**Issue by wonhui-kim** [wonhui-kim/DeunDeunHaSom_#5]
## 💡 Issue

비대한 코드 등 가독성 있는 코드로 변경하기 위해 리팩토링

## 📝  todo
- [ ] final, private 키워드 체크하고 붙이기
- [ ] url 관리 방법 모색하여 따로 관리하기
- [ ] requestData, todayMenus 함수 길이 줄이기

## 참고한 코드 출처
- []()
